on: [push, pull_request]
jobs:
  deploy:
    name: Notify AWS Pubsub and trigger Spinnaker
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from psdev account
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.SPINNAKER_ASSUME_ROLE }}
        role-session-name: MySessionName

    - name: Trigger Spinnaker with Pubsub
      uses: alchen99/spinnaker-pipeline-trigger@v1.3.0
      with:
        aws_region: us-east-1
        topic_arn: ${{ secrets.SPINNAKER_TOPIC_ARN }}
        parameters: |
          param1: fromGHA
